export const FETCH_CURRENT_POPULATION_DATA = 'FETCH_CURRENT_DATA';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';


export const FETCH_ALL_COUNTRIES ="FETCH_ALL_COUNTRIES";
export const FETCH_ALL_YEARS ="FETCH_ALL_YEARS";