export const FETCH_CURRENT_POPULATION_DATA = "FETCH_CURRENT_DATA";
export const FETCH_CURRENT_EMISSIONS_DATA = "FETCH_CURRENT_EMISSIONS_DATA";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";

export const FETCH_ALL_COUNTRIES = "FETCH_ALL_COUNTRIES";
export const FETCH_ALL_YEARS = "FETCH_ALL_YEARS";

export const GET_BIGGEST_EMITTERS_IN_SPECIFIC_YEAR =
  "GET_BIGGEST_EMITTERS_IN_SPECIFIC_YEAR";

export const GET_YEARS_INTERVAL_POPULATION_DATA = "GET_YEARS_INTERVAL_POPULATION_DATA";
export const GET_YEARS_INTERVAL_EMISSIONS_DATA = "GET_YEARS_INTERVAL_EMISSIONS_DATA";
